#!/bin/bash

gcc sign.c -o ./sign
./sign < /usr/share/dict/words |
oldL=$LANG LANG=C sort | #Here I have to change the language and change it back due to preset ignorecasing
LANG=$oldL awk -f squash.awk | 
awk '{print NF " " $0}' |
sort -n -r |
head -n 8 |
cat
